# Generated by Django 3.0.3 on 2020-04-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_contract', models.TextField()),
                ('dorm_rule', models.TextField()),
                ('room_rate', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(max_length=255)),
                ('dorm_owner', models.CharField(max_length=255)),
                ('open_time', models.DateTimeField()),
                ('address', models.TextField()),
                ('floor', models.IntegerField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_service_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_fac_id', models.CharField(max_length=5)),
                ('service_types_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(max_length=10)),
                ('room_rate', models.FloatField()),
                ('floor', models.IntegerField(max_length=10)),
                ('dormitory_dorm_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_gen', models.CharField(max_length=255)),
                ('contract_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residents.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Room_contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residents.Contract')),
                ('room_room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residents.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_date', models.DateField()),
                ('month_no', models.IntegerField()),
                ('room_rate', models.FloatField()),
                ('water_ex', models.FloatField()),
                ('elec_ex', models.FloatField()),
                ('contract_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residents.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_rate', models.FloatField()),
                ('dormitory_dorm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residents.Dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField()),
                ('exp_rate', models.FloatField()),
                ('exp_title', models.CharField(max_length=50)),
                ('invoice_inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residents.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='resident_resident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residents.Resident'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('resident_resident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residents.Resident')),
            ],
        ),
    ]
